// Copyright 2016 - 2020 Code 4 Game, Inc. All Rights Reserved.
// Don't edit this, it will be generated by builder.

#pragma once

#define GLTFFORUE4_MAJOR_VERSION 0
#define GLTFFORUE4_MINOR_VERSION 0
#define GLTFFORUE4_PATCH_VERSION 0
#define GLTFFORUE4_BUILD_NUMBER 0
